%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MDN month average
% Takes MDNsort data, and averages it daily and then monthly
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Run setup - import data from files
GreatLakesMDN

%To run sktt and store values
%Change site name to desired site
[taubsea tausea Sens h sig sigAdj Zs Zmod Ss Sigmas CIlower CIupper] = sktt(WI08dep, 0.05, 1)

%% Plotting 2013 averages at all sites
k = 0:11;
figure;
subplot(3,3,1);
plot(k,MDN00mn(:,36));
title('MDN00');
subplot(3,3,2);
plot(k,MDN01mn(:,36));
title('MDN01');
subplot(3,3,3);
plot(k,MDN02mn(:,36));
title('MDN02');
subplot(3,3,4);
plot(k,MDN04mn(:,36));
title('MDN04');
subplot(3,3,5);
plot(k,MDN09mn(:,36));
title('MDN09');
subplot(3,3,6);
plot(k,MDN20mn(:,36));
title('MDN20');
subplot(3,3,7);
plot(k,MDN43mn(:,36));
title('MDN43');
subplot(3,3,8);
plot(k,MDN96mn(:,36));
title('MDN96');
subplot(3,3,9);
plot(k,MDN98mn(:,36));
title('MDN98');
%% Great Lakes by year
ylimit = 200;

figure;
subplot(5,2,1);
plot(MN18sort(:,5),MN18sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MN18 1996');
subplot(5,2,2);
plot(WI08sort(:,5),WI08sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('WI08');
subplot(5,2,3);
plot(WI36sort(:,5),WI36sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('WI36');
subplot(5,2,4);
plot(MI48sort(:,5),MI48sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MI48');
subplot(5,2,5);
plot(MN16sort(:,5),MN16sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MN16');
subplot(5,2,6);
plot(MN23sort(:,5),MN23sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MDN20');
subplot(5,2,7);
plot(MN22sort(:,5),MN22sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MN22');
subplot(5,2,8);
plot(MN98sort(:,5),MN98sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MN98');
subplot(5,2,9);
plot(MN27sort(:,5),MN27sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MN27');
subplot(5,2,10);
plot(MN06sort(:,5),MN06sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MN06');

figure;
subplot(5,2,1);
plot(MI09sort(:,5),MI09sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MI09 1996');
subplot(5,2,2);
plot(MI26sort(:,5),MI26sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MI26');
subplot(5,2,3);
plot(MI52sort(:,5),MI52sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('MI52');
subplot(5,2,4);
plot(IL11sort(:,5),IL11sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('IL11');
subplot(5,2,5);
plot(IL63sort(:,5),IL63sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('IL63');
subplot(5,2,6);
plot(IN21sort(:,5),IN21sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('IN21');
subplot(5,2,7);
plot(IN22sort(:,5),IN22sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('IN22');
subplot(5,2,8);
plot(IN34sort(:,5),IN34sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('IN34');
subplot(5,2,9);
plot(WI10sort(:,5),WI10sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('WI10');
subplot(5,2,10);
plot(WI31sort(:,5),WI31sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('WI31');

figure;
subplot(5,2,1);
plot(OH02sort(:,5),OH02sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('OH02 1996');
subplot(5,2,2);
plot(OH52sort(:,5),OH52sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('OH52');
subplot(5,2,3);
plot(NY06sort(:,5),NY06sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('NY06');
subplot(5,2,4);
plot(NY20sort(:,5),NY20sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('NY20');
subplot(5,2,5);
plot(NY43sort(:,5),NY43sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('NY43');
subplot(5,2,6);
plot(NY68sort(:,5),NY68sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('NY68');
subplot(5,2,7);
plot(NY96sort(:,5),NY96sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('NY96');
subplot(5,2,8);
plot(PA00sort(:,5),PA00sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA00');
subplot(5,2,9);
plot(PA13sort(:,5),PA13sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA13');
subplot(5,2,10);
plot(PA18sort(:,5),PA18sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA18');

figure;
subplot(6,2,1);
plot(PA21sort(:,5),PA21sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA21 1996');
subplot(6,2,2);
plot(PA29sort(:,5),PA29sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA29');
subplot(6,2,3);
plot(PA30sort(:,5),PA30sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA30');
subplot(6,2,4);
plot(PA37sort(:,5),PA37sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA37');
subplot(6,2,5);
plot(PA42sort(:,5),PA42sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA42');
subplot(6,2,6);
plot(PA47sort(:,5),PA47sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA47');
subplot(6,2,7);
plot(PA52sort(:,5),PA52sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA52');
subplot(6,2,8);
plot(PA60sort(:,5),PA60sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA60');
subplot(6,2,9);
plot(PA72sort(:,5),PA72sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA72');
subplot(6,2,10);
plot(PA90sort(:,5),PA90sort(:,7));
datetick('x', 'mmm', 'keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('PA90');
subplot(6,2,11);
plot(ON07sort(:,5),ON07sort(:,7));
datetick('x','mmm','keepticks');
xlabel('Date');
ylabel('HGDEP [pg/m^3]');
ylim ([0 ylimit]);
title('ON07');

%% Medians for 1996-2000
WI08_96 = zeros(1830,1);
WI08_96(1:366) = WI08dy(:,3);
WI08_96(367:732) = WI08dy(:,7); 
WI08_96(733:1098) = WI08dy(:,11);
WI08_96(1099:1464) = WI08dy(:,15);
WI08_96(1465:1830) = WI08dy(:,19);
